SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{65D341B8C66ED4DA}" {
     m_sEntityPrefab "{F0F9596503114D4C}Prefabs/Items/Equipment/Radios/Radio_AN/Radio_ANARC231.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{65D341B8C66ED482}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{690402A119180CB6}" {
     m_sEntityPrefab "{380541B57B48897D}Prefabs/Items/Equipment/Radios/Radio_AN/Radio_ANARC231_TW.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690402A119180C5A}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{690402A117802DAC}" {
     m_sEntityPrefab "{15E7A50DA3E2299F}Prefabs/Items/Equipment/Radios/Radio_AN/Radio_ANARC231_WR.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690402A117802D5E}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}