SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{65EF57CB52782B85}" {
   m_sName "TDL"
   m_sDisplayName "TDL"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{65EF57CB594CF530}" {
     m_sActionName "OpenTDLMenu"
     m_sDisplayName "Open TDL Menu"
     m_sPreset "TDL_MenuToggle"
    }
    SCR_KeyBindingEntry "{67396487CB480840}" {
     m_sActionName "TDLAdjustUp"
     m_sDisplayName "Flip Up ATAK"
     m_sPreset "TDLAdjustUp"
     m_ePrefixType AMBIGUOUS
    }
    SCR_KeyBindingEntry "{673964863BF0DF98}" {
     m_sActionName "TDLAdjustDown"
     m_sDisplayName "Flip Down ATAK"
     m_sPreset "TDLAdjustDown"
     m_ePrefixType AMBIGUOUS
    }
    SCR_KeyBindingEntry "{672776C12F10C770}" {
     m_sActionName "TDLPanHorizontal"
     m_sDisplayName "Pan Horizontal"
     m_sPreset "TDLPanHorizontal"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{672776C11CF29CB6}" {
     m_sActionName "TDLPanVertical"
     m_sDisplayName "Pan Vertical"
     m_sPreset "TDLPanVertical"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{695A314BE4B42622}" {
     m_sActionName "TDLFocusToggle"
     m_sDisplayName "Toggle Device Focus"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{695A314A86855DA4}" {
     m_sActionName "TDLCursorUp"
     m_sActionNameGamepadOptional "TDLCursorGamepadUp"
     m_sDisplayName "Cursor Up"
     m_sPreset "up"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{695A314B35C6D86E}" {
     m_sActionName "TDLCursorDown"
     m_sActionNameGamepadOptional "TDLCursorGamepadDown"
     m_sDisplayName "Cursor Down"
     m_sPreset "down"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{695A314B4FBCC44A}" {
     m_sActionName "TDLCursorLeft"
     m_sActionNameGamepadOptional "TDLCursorGamepadLeft"
     m_sDisplayName "Cursor Left"
     m_sPreset "left"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{695A314AD28AC7B0}" {
     m_sActionName "TDLCursorRight"
     m_sActionNameGamepadOptional "TDLCursorGamepadRight"
     m_sDisplayName "Cursor Right"
     m_sPreset "right"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{6961453D7D00B1C6}" {
     m_sActionName "TDLDraw"
     m_sDisplayName "Draw"
     m_sPreset "hold"
     m_ePrefixType CONTINUOUS
    }
   }
  }
 }
}